services:
  api-gateway:
    image: ghcr.io/wuuanito/api-gateway:${API_GATEWAY_TAG:-latest}
    ports: ["6000:8000"]
    depends_on: [mongo, auth-service]
    restart: unless-stopped
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - WEBSOCKET_SERVICE_URL=http://192.168.11.7:6003
      - NODE_ENV=production

  auth-service:
    image: ghcr.io/wuuanito/auth-service-microservice:${AUTH_TAG:-latest}
    ports: ["6001:3001"]
    depends_on: [mongo]
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auth
      - NODE_ENV=production

  websocket-server:
    image: ghcr.io/wuuanito/websocket-server:${WEBSOCKET_TAG:-latest}
    ports: ["6003:6003"]
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=6003

  mongo:
    image: mongo:6.0
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
    restart: unless-stopped

volumes:
  mongo-data:
